name: cron

on:
  schedule:
    # Cron job every day at 12:00
    # https://crontab.guru/#0_12_*_*_*
    - cron: '12 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - name: Setup Puppeteer
        run: npx puppeteer browsers install chrome
      - name: Cron
        run: |
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USERNAME }}
          DEBUG='tesla-specifications*' node scripts/specifications.js
          (git add src/index.json && git commit -m 'build(cron): update specifications' --no-verify && git push) || true
          curl -fsS -m 10 --retry 5 -o /dev/null https://hc-ping.com/3cb379bd-82f5-49c1-9f54-6e9f314aa7ba
